apiVersion: v1
kind: Service
metadata:
  name: wis-service-http
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: wis
  ports:
    - name: output
      port: 8080
      targetPort: 8080
      protocol: TCP
  externalTrafficPolicy: Local