apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJncm9tYWNob3J0aSIsInBhc3N3b3JkIjoiTW9udC1MZXJveS42NiEiLCJhdXRoIjoiWjNKdmJXRmphRzl5ZEdrNlRXOXVkQzFNWlhKdmVTNDJOaUU9In19fQ==
kind: Secret
metadata:
  name: docker-hub
  namespace: default
type: kubernetes.io/dockerconfigjson
