apiVersion: apps/v1
kind: StatefulSet #CHANGE OF DEPLOYMENT TO STATEFULL
metadata:
  labels:
    app: fms
  name: fms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fms
  template:
    metadata:
      labels:
        app: fms
    spec:
      imagePullSecrets:
        - name: docker-hub
      containers:
        - name: fms
          image: rticom/fleet_managment_service:6.9.0
          imagePullPolicy: Always
          env:
            - name: NDDS_DISCOVERY_PEERS
              value: {{ .Values.CDS_CLUSTER_IP }} #Internal CDS CLUSTER IP
              # value: "rtps@udpv4://10.100.14.152:7400"

          command: ["python3"]
          args: ["fleet_participant.py"]

          ports:
            - containerPort: 8080
          volumeMounts:
            - name: license-volume
              mountPath: /opt/rti.com/rti_connext_dds-7.3.0/rti_license.dat 
              subPath: rti_license.dat
      volumes:
          - name: license-volume
            configMap:
              name: rti-license
              defaultMode: 0777

